module.exports = {
  apps: [
    {
      name: "api-current",
      script: "./apps/api/dist/main.js",
      cwd: "/srv/poolcare",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 4000,
      },
      error_file: "./logs/api-error.log",
      out_file: "./logs/api-out.log",
      merge_logs: true,
      autorestart: true,
      max_memory_restart: "500M",
    },
    {
      name: "api-next",
      script: "./apps/api/dist/main.js",
      cwd: "/srv/poolcare",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 4001,
      },
      error_file: "./logs/api-next-error.log",
      out_file: "./logs/api-next-out.log",
      merge_logs: true,
      autorestart: true,
      max_memory_restart: "500M",
    },
    {
      name: "web-current",
      script: "./apps/web/.next/standalone/server.js",
      cwd: "/srv/poolcare",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      error_file: "./logs/web-error.log",
      out_file: "./logs/web-out.log",
      merge_logs: true,
      autorestart: true,
      max_memory_restart: "500M",
    },
    {
      name: "worker-notify",
      script: "./apps/workers/dist/notify.js",
      cwd: "/srv/poolcare",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/worker-notify-error.log",
      out_file: "./logs/worker-notify-out.log",
      merge_logs: true,
      autorestart: true,
    },
    {
      name: "worker-files",
      script: "./apps/workers/dist/files.js",
      cwd: "/srv/poolcare",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/worker-files-error.log",
      out_file: "./logs/worker-files-out.log",
      merge_logs: true,
      autorestart: true,
    },
    {
      name: "worker-ai",
      script: "./apps/workers/dist/ai.js",
      cwd: "/srv/poolcare",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/worker-ai-error.log",
      out_file: "./logs/worker-ai-out.log",
      merge_logs: true,
      autorestart: true,
    },
  ],
};

